### ISSUE TITLE
Map not avilable

### ISSUE THREAD

**Issue by nicholasbennet** [osm-in/flood-map#18]
The map has gone offline and we are not able to view the map.

**Comment by planemad** [comment]
@nicholasbennet can you recheck? seems to be working fine.

**Comment by rcanand** [comment]
I can also confirm that the map is not available on the site - the left side animation is running, but there is no map in the main area - just the box with the 'Learn More' link. Update: Does not work with Chrome on Mac. It does work with Safari on Mac.

**Comment by planemad** [comment]
More details on the browser you are using?

**Comment by eternaltyro** [comment]
Works for me on Firefox and Chromium.

**Comment by nicholasbennet** [comment]
It was not working on firefox for windows for some time. Now its working.
Awesome initiative by the way. Helped a lot in cordinating evacuations.

Nicholas

**Comment by planemad** [comment]
Thanks @nicholasbennet, it means a lot to know such tools make a difference on the ground.

Closing this for now, guess this might have been a stray issue due to the huge load.
