### ISSUE TITLE
Easier way to retrieve the latest geo data?

### ISSUE THREAD

**Issue by netvarun** [osm-in/flood-map#20]
Current method states to 'Download the latest flooded streets layer as a geojson using this Ajax request.'

However it's a little clunky especially when operating on a headless, serverside environment.

At the moment, I am doing a  'Copy All as HAR'  on Chrome Dev Inspector to a JSON text file and then parsing out the AJAX queries via perl next if $url !~ /api.mapbox.com\/datasets\/v1\/chennaiflood\/cihoxpoqp0000vjkq160aw68g\/features\?access_token/;

Is there a more direct, simpler, programmatic way to do that? Preferably one direct curl request to dump out all the data in JSON format.

[Btw, we are using this to power http://chennai-akkarai.ngrok.com Thanks for all the work! ]

**Comment by planemad** [comment]
@netvarun the Mapbox data API we use has a hardcoded request limit of 100 features. Am storing the final JSON as a global variable `dump`. If you access that in your console you should get the whole stringified GeoJSON. Hope that helps.
