### ISSUE TITLE
Redeploying flood map for St. Louis

### ISSUE THREAD

**Issue by planemad** [osm-in/flood-map#23]
Just got this message on my [Wikipedia page](https://en.wikipedia.org/wiki/User_talk:Planemad#Flood_Maps)

> Hello,
> I saw your flood map, St. Louis Missouri USA could use your right now!
> Is this something that can be deployed quickly or something that takes backend time to setup?
> Ideally if you could set this up so that it could be used anywhere on top of google maps for emergencies.

There is a flood warning in [Missouri right now](http://edition.cnn.com/2015/12/30/us/severe-weather-us/) and is a good use case for making flood-map a reusable tool to crowdsource information during future emergencies.

@batpad @geohacker @arunasank what does it take to redeploy this for a new location? Also how can we make this community owned so that anyone can redeploy in times of crisis?

**Comment by planemad** [comment]
Another request for the Baton Rouge flooding

<img width="579" alt="screenshot 2016-08-17 19 09 22" src="https://cloud.githubusercontent.com/assets/126868/17738264/30777204-64ae-11e6-9b3a-89f7c2f94d19.png">

**Comment by arky** [comment]
Looks like the forked U-Flood (https://u-flood.com/) codebase has necessary scripts for quick deployments.

Checkout the code base here:
https://github.com/tailwindlabs/flood-map

I really like their zoom and tap to report flooding features.

**Comment by planemad** [comment]
Thank you @nickmcintyre ❤️
