### ISSUE TITLE
custom mapbox styles

### ISSUE THREAD

**Issue by nullart** [osm-in/flood-map#24]
Hi,

I've been trying to build a mapbox styles, but it doesn't seem to work as I am getting errors like: 

`Uncaught TypeError: Cannot read property 'geometry' of undefined`

How do we add our custom mapbox style? Maybe a step by step guide?

All the best!

**Comment by planemad** [comment]
@nullart documentation to use Mapbox GL is here https://mapbox.com/mapbox-gl-js/examples . There are tutorials here https://www.mapbox.com/help/

Please reopen if you have specific issues with the flood map

**Comment by nullart** [comment]
I have seen these and have tried this, but the current example does not help as I'm getting an error when clicking a road:

![screen shot 2017-01-18 at 8 11 41 am](https://cloud.githubusercontent.com/assets/448013/22045553/e7012d6a-dd55-11e6-8c4b-4dbe86c2631f.png)

using the example from here:  https://mapbox.com/mapbox-gl-js/examples

`
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/streets-v9', //stylesheet location
    center: [-74.50, 40], // starting position
    zoom: 9 // starting zoom
});
`

Clearly, your mapbox style is configured differently than the mapbox styles out of the box. Maybe you can shed a light on this?

**Comment by nullart** [comment]
PS: I cannot re-open this issue

**Comment by planemad** [comment]
@nullart can you share your full html or js? Its not possible to debug without seeing the rest of the code.

**Comment by nullart** [comment]
@planemad 

this is the only change i made in chennai.js:

`
// Define map locations
var mapLocation = {
    'reset': {
        'center': [124.6458,8.4776],
        'zoom': 13.8,
        'pitch': 0,
        'bearing': 0
    }
};

// Simple map
mapboxgl.accessToken = 'pk.eyJ1IjoibnVsbGFydCIsImEiOiJjaXkwbHV2eGkwMGEwMzNsbXcxYzcyb2YwIn0.o1Mv6BothDFsg8E9uDsCcA';
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/streets-v9', //stylesheet location
    hash: true
});
`

**Comment by nullart** [comment]
anyway, just to inform you that I'm planning to deploy this for my city. As we recently have been hit by flood.

**Comment by planemad** [comment]
@nullart just checked with your code and i'm seeing it work as expected. Can you please push your code to a branch or share your repository?

**Comment by nullart** [comment]
hi @planemad  I have updated the the forked repository. The settings are in js/cdeo.js and the above code has been commented. I'm using your style atm so I can deploy it for my city.

The problem with using custom mapbox style, when clicking a road (in color white). With yellow or gold colored road, it works sometimes.

**Comment by planemad** [comment]
@nullart got it.

You need to make sure the [road layer ids](https://github.com/nullart/flood-map/blob/gh-pages/js/cdeo.js#L55-L75) match the road related layer id's in your custom style. You can verify this by opening the style you are using in Mapbox Studio.

<img width="287" alt="screenshot 2017-01-19 10 23 43" src="https://cloud.githubusercontent.com/assets/126868/22094189/93ed9abe-de31-11e6-9cbd-499f7f44ce3b.png">

If you click on the road in the Studio map, it should list the layer ids you need to be able to query.

**Comment by nullart** [comment]
hi @planemad I tried it but it doesn't work. I think that the issue is with (correct me if I'm wrong) [map.featuresAt](https://github.com/nullart/flood-map/blob/gh-pages/js/cdeo.js#L221-L250). The new styles saved at mapbox does not seem to support featuresAt anymore. 

featuresAt has been removed since version [0.16.0](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#0160-march-24-2016)

**Comment by planemad** [comment]
@nullart thats right, you need to use the old Mapbox GL. Have yet to port this to the new version. But if you want a pointer on how it can be done with the new map.queryRenderedFeatures function see https://github.com/osmlab/fieldnotes/blob/master/index.js#L81

**Comment by nullart** [comment]
Thanks, I'm working on it, will try to port it to the new mapboxgl. Will inform you of my progress. 

Cheers!
