### ISSUE TITLE
Redeploying FloodMaps for Kerala's floods!

### ISSUE THREAD

**Issue by NishanthN1** [osm-in/flood-map#30]
Hello there! This map was of immense use during the Chennai floods. Wouldn't it be a good idea to redeploy this for the Kerala floods now in 2018, and spread the word? At least in major towns and cities this should be of great use!

**Comment by cyriacbijun** [comment]
Yes,everyone who is available please contributing an app to help the flood affected victims of Kerala

**Comment by arunasank** [comment]
Hello everyone @kishorv06 has set this up at https://www.microid.in/keralaflood.

**Comment by NishanthN1** [comment]
Thank you for letting us know about this! I'm sharing this right away!

**Comment by cyriacbijun** [comment]
Yes,me too,this is an awesome application
