### ISSUE TITLE
High traffic is bringing down the database

### ISSUE THREAD

**Issue by rajavm** [osm-in/flood-map#4]
I tried all ways to mark water logged points in the map but in vain
How to add them? 
https://osm-in.github.io/flood-map/chennai.html#19/13.09008/80.19136

**Comment by planemad** [comment]
@rajavm looking into it. Thanks for reporting.

**Comment by VIJAYCHARAN** [comment]
I face the same problem. couldn't mark the inundated area..

**Comment by planemad** [comment]
Seems like the sudden surge in traffic is bringing down the database. We're doing our best to keep it up, but might have to wait till morning to move it to a more stable server.

Added an error message for the users now.

**Comment by planemad** [comment]
cc @batpad @geohacker

**Comment by jashjacob** [comment]
Still not able to mark the areas.

**Comment by planemad** [comment]
@jashjacob we should be up again within two hours.

**Comment by eternaltyro** [comment]
Is the data on a database separate from standard OSM DB?

**Comment by geohacker** [comment]
@eternaltyro - that's correct, yes.

**Comment by planemad** [comment]
We're back up now, thanks @batpad @geohacker

**Comment by planemad** [comment]
Still seems to have intermittent issues. Looking into it.

**Comment by iraxl** [comment]
Hi Guys - To help offload the main site, I cloned the project and copied the map layer at:

http://www.postsp.in

I also have setup a cron job to pull the updated map layer every 30 mins to keep up to date. 

Please feel free to spread the link.

**Comment by batpad** [comment]
thanks @iraxl . We have managed to fix this though by moving to AWS auto-scaling infrastructure. Closing.
